### ISSUE TITLE
Unexpected API error. KeyError: com.github.brpaz.ulauncher-github

### ISSUE THREAD

**Issue by AnasR7** [brpaz/ulauncher-github#1]
![image](https://user-images.githubusercontent.com/23519166/45502607-a11c9e80-b7ae-11e8-89c2-4b21427a76c3.png)

i just got this error..

and cannot to add github to my extension.

**Comment by brpaz** [comment]
Hello. Please install "pygithub" python package like explained in the README. It should work then.

**Comment by AnasR7** [comment]
I have already tried pip install pygithub via sudo.

and still get this error

this is my sc:
![image](https://user-images.githubusercontent.com/23519166/45521532-9b43af00-b7e8-11e8-8f6e-e0ef73b8d13e.png)

**Comment by brpaz** [comment]
Can you try to remove the extension and install it again?
If it does not work, close Ulauncher, and run it from the command line: `ulauncher -v` and paste it there any errors you could find in the output.

**Comment by ironicbadger** [comment]
`python-pygithub` is installed (running Arch with Plasma).

```
2018-12-29 01:07:53,956 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_add() | Add extension: https://github.com/brpaz/ulauncher-github
2018-12-29 01:07:54,666 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-github" started. PID 13172
/home/alex/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-github/main.py:9: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "/home/alex/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-github/main.py", line 10, in <module>
    from github import Github, GithubException
ImportError: No module named github
2018-12-29 01:07:54,739 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-github" exited instantly with code 1
2018-12-29 01:08:01,627 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_update_prefs() | Update extension preferences: {'pref.kw_search': 'ghsearch', 'callback': '__jp4', 'pref.access_token': '75cd33fd73879fe63136dadbf01af7695df2e91f', 'pref.kw': 'gh', 'pref.kw_gists': 'gists', 'id': 'com.github.brpaz.ulauncher-github', 'pref.kw_repos': 'ghrepos'}
2018-12-29 01:08:01,628 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.brpaz.ulauncher-github
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/site-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'
```

**Comment by brpaz** [comment]
@IronicBadger  I think you might have installed the wrong package.

```
pip install PyGithub
```

**Comment by rajalokan** [comment]
Just installing `pygithub` using pip didn't solve for me. Removing extension form ulauncher and re-installing again did the trick. Thanks.

**Comment by estorbito** [comment]
BTW check the log (ulauncher -v) and search devdocs errors. In my case, python-requests was missing on my system.
