### ISSUE TITLE
error on setting PAT

### ISSUE THREAD

**Issue by verajosemanuel** [brpaz/ulauncher-github#14]
Installed ok, then created a new Personal Access Token and then pasted to settings. Then error arised

Message: 'com.github.brpaz.ulauncher-github'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'

```

**Comment by brpaz** [comment]
Please confirm that you have all the required python dependencies installed. namely pygithub

This process should be improved when this issue is done on the Ulauncher side https://github.com/Ulauncher/Ulauncher/issues/273

Feel free to reopen if the problem persists
