### ISSUE TITLE
UnhandledError -> com.github.brpaz.ulauncher-github

### ISSUE THREAD

**Issue by Coyas** [brpaz/ulauncher-github#4]
Message: 'com.github.brpaz.ulauncher-github'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'

```
I am trying to make change on github keyword but it show me this error

**Comment by brpaz** [comment]
Have you installed `pygithub` like specified  in [Requeriments](https://github.com/brpaz/ulauncher-github#requirements) section of the README?

Make sure you have installed with pip3, not pip. I have updated the README just now to reflect that.

**Comment by Natetronn** [comment]
I get the same error and I installed via pip3 per the updated README.

Message: 'com.github.brpaz.ulauncher-github'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-github'

```
