### ISSUE TITLE
gh search does not return results

### ISSUE THREAD

**Issue by steve-todorov** [brpaz/ulauncher-github#6]
## Description

If you type `gh search symfony` or `gh gists` it will return the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/steve/.local/share/ulauncher/extensions/com.github.brpaz.ulauncher-github/main.py", line 470, in on_event
    return extension.search_public_repos(search[0].strip())
  File "/home/steve/.local/share/ulauncher/extensions/com.github.brpaz.ulauncher-github/main.py", line 353, in search_public_repos
    on_alt_enter=CopyToClipboardAction(repo.html_url)))
  File "/usr/lib/python3/dist-packages/ulauncher/api/shared/item/ExtensionResultItem.py", line 18, in __init__
    super(ExtensionResultItem, self).__init__(*args, **kw)
  File "/usr/lib/python3/dist-packages/ulauncher/api/shared/item/ResultItem.py", line 44, in __init__
    raise TypeError('"description" must be of type "str", "%s" given' % type(description).__name__)
TypeError: "description" must be of type "str", "bytes" given
```

## Environment info
```
$ lsb_release  -a
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

$ ulauncher --version
ulauncher 5.7.0

$ python3 --version
Python 3.7.5

$ pip3 list | grep -i pygit
PyGithub 1.46 
```

**Comment by brpaz** [comment]
fixed in #7
